name: Build with Buildroot and upload artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Buildroot dependencies
        run: sudo apt-get update && sudo apt-get install -y git fakeroot qemu-user-static

      - name: Clone Buildroot
        run: git clone https://github.com/Entersjkhdfkjdhfksjf/buildrootx.git

      - name: Configure Buildroot (x86_64)
        run: |
          cp newconf buildroot/configs
          cd buildroot
          make warp7_defconfig

      - name: Build the image
        run: |
          cd buildroot
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts # Customize the artifact name
          path: buildroot/output/images/ # Path to artifacts
          
