name: Build with Buildroot and upload artifacts

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Buildroot dependencies
        run: sudo apt-get update && sudo apt-get install -y git syslinux fakeroot qemu-user-static

      - name: Clone Buildroot
        run: git clone https://github.com/Entersjkhdfkjdhfksjf/buildrootx.git

      - name: Configure Buildroot (x86_64)
        run: |
          cp newconf buildrootx/configs
          cd buildrootx
          make warp7_defconfig

      - name: Build the image and install bootloader
        run: |
          cd buildrootx
          make
          cd output/images
          syslinux rootfs.iso

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts # Customize the artifact name
          path: buildrootx/output/images/ # Path to artifacts
          
